schemaVersion = 1

[extensions]
enabledIdentifiers = [ 'com.brnbw.tuna.plugins.cleanshot' ]

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[hotkeys.app.leaderMode]
carbonKeyCode = 49
carbonModifiers = 2048

[hotkeys.app.textMode]
carbonKeyCode = 49
carbonModifiers = 4096

[[hotkeys.custom]]
id = '1FF7A769-1A0C-46D1-9C9E-F14045B38A76'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'TunaEmoji.EmojiSearchCatalog.Emoji'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 14
    carbonModifiers = 6912

[[hotkeys.custom]]
id = 'E46E02E2-E179-49B0-9CF9-553128B0844F'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'Tuna.Internal.ClipboardProxyCatalog.Clipboard History'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 8
    carbonModifiers = 768

[[hotkeys.custom]]
id = 'E59C1C8E-5694-46B3-BE39-2B2AE3654B59'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Run'
    subjectIdentifier = 'TunaSystem.ColorToolsCatalog.Pick Color'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 35
    carbonModifiers = 768

[[leaderMode.bindings]]
iconPath = '/Applications/Ghostty.app'
key = 'enter'
label = 'Ghostty'
url = 'tuna://run/text.open%2520-na%2520Ghostty.app/Run%20Text%20as%20Shell%20Command'

[[leaderMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fhasse%252FDownloads/Open'

[[leaderMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fhasse/Open'

[[leaderMode.bindings]]
key = 'b'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Brave%20Browser/Open'

[[leaderMode.bindings]]
iconPath = 'face.smiling'
key = 'y'
url = 'tuna://run/TunaEmoji.EmojiSearchCatalog.Emoji/Tuna.BasicActionsCatalog.Browse'

[[leaderMode.bindings]]
iconPath = 'paperplane.fill'
key = 'a'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

    [[leaderMode.bindings.children]]
    key = 'f'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.FMail3/Open'

    [[leaderMode.bindings.children]]
    key = 'p'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.PhpStorm/Open'

    [[leaderMode.bindings.children]]
    key = 'r'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Ray/Open'

[[leaderMode.bindings]]
key = 'c'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/url.https:%252F%252Fmymarks.net/Open%20URL'

[settings]
leaderModeThemeStyle = 'cheatsheet'
themeIdentifier = 'com.brnbw.tuna.themes.default'

[[smartLinks.entries]]
enabled = true
name = 'Academicbooks ISBN'
requiresInput = true
template = 'https://academicbooks.dk/model/{{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Kagi.com'
requiresInput = true
template = 'https://kagi.com/search?q={{input}}'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'custom:4FFFA7'